In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
crime_report = pd.read_excel('C:/Users/Administrator/Desktop/coding/DataScience/data/report..xlsx', encoding='utf-8')
crime_report.head()

기간      구분      계  아파트 연립다세대   단독주택    노상    상점  숙박업소목욕탕  유흥접객업소  사무실  \
0  2017       계   4523       5092  32063  5047  1437     5077    1772  908   
1  2017      살인    142         21     25    27     1        5      10    5   
2  2017      강도    169         20     11    43    22        8       5    5   
3  2017  강간강제추행   6963        319    413  1061   116      408     495  130   
4  2017      절도  41162       1209   1340  8255  4119      670    1809  564   

   역대합실  교통수단  유원지    학교   금융기관     기타  
0  2359   754  518  1024  47261      0  
1     0     1    1     0      0     46  
2     1     0    1     0      3     50  
3   242  1105   51    49      1   2573  
4   335   744  282   247    990  20598

In [17]:
crime_report.iloc[[1],[1,10]]

구분  역대합실
1  살인     0

In [22]:
crime_report.rename(columns={crime_report.columns[1]:'범죄구분',
                            crime_report.columns[2]:'5대범죄'}, inplace=True)
crime_report.head()                    

기간    범죄구분   5대범죄  아파트 연립다세대   단독주택    노상    상점  숙박업소목욕탕  유흥접객업소  사무실  \
0  2017       계   4523       5092  32063  5047  1437     5077    1772  908   
1  2017      살인    142         21     25    27     1        5      10    5   
2  2017      강도    169         20     11    43    22        8       5    5   
3  2017  강간강제추행   6963        319    413  1061   116      408     495  130   
4  2017      절도  41162       1209   1340  8255  4119      670    1809  564   

   역대합실  교통수단  유원지    학교   금융기관     기타  
0  2359   754  518  1024  47261      0  
1     0     1    1     0      0     46  
2     1     0    1     0      3     50  
3   242  1105   51    49      1   2573  
4   335   744  282   247    990  20598

In [24]:
np.corrcoef(crime_report['5대범죄'], crime_report['아파트 연립다세대'])

array([[1.        , 0.27347424],
       [0.27347424, 1.        ]])

In [26]:
np.corrcoef(crime_report['5대범죄'], crime_report['단독주택'])

array([[ 1.        , -0.18444586],
       [-0.18444586,  1.        ]])

In [25]:
np.corrcoef(crime_report['5대범죄'], crime_report['노상'])

array([[1.        , 0.92933447],
       [0.92933447, 1.        ]])

In [27]:
np.corrcoef(crime_report['5대범죄'], crime_report['상점'])

array([[1.        , 0.50925131],
       [0.50925131, 1.        ]])

In [28]:
np.corrcoef(crime_report['5대범죄'], crime_report['유흥접객업소'])

array([[1.        , 0.84756912],
       [0.84756912, 1.        ]])

In [29]:
np.corrcoef(crime_report['5대범죄'], crime_report['사무실'])

array([[1.        , 0.69955086],
       [0.69955086, 1.        ]])

In [30]:
np.corrcoef(crime_report['5대범죄'], crime_report['역대합실'])

array([[ 1.        , -0.13556873],
       [-0.13556873,  1.        ]])

In [31]:
np.corrcoef(crime_report['5대범죄'], crime_report['교통수단'])

array([[1.        , 0.24367999],
       [0.24367999, 1.        ]])

In [32]:
np.corrcoef(crime_report['5대범죄'], crime_report['유원지'])

array([[1.        , 0.53784399],
       [0.53784399, 1.        ]])

In [33]:
np.corrcoef(crime_report['5대범죄'], crime_report['학교'])

array([[ 1.        , -0.01113161],
       [-0.01113161,  1.        ]])

In [34]:
np.corrcoef(crime_report['5대범죄'], crime_report['금융기관'])

array([[ 1.        , -0.26709548],
       [-0.26709548,  1.        ]])